### ISSUE TITLE
Integration with ROS1

### ISSUE THREAD

**Issue by hisham246** [bardhh/cbfkit#3]
Can this framework be integrated with ROS1? I am interested on using CBFKit with robotic manipulators that do not yet have functional support on ROS2.

**Comment by bardhh** [comment]
Thank you for your interest in CBFKit. Currently, integration with ROS1 is not supported. The framework is designed to work with ROS2. Perhaps the generated ROS2 scripts could help you write the ROS1 scripts faster.
